name: test

on:
  push:
  merge_group:
  
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
       name: production
    steps:
      - name: test
        run: curl -i -H "Authorization:Token ${{GITHUB_TOKEN}}" "https://api.github.com/user"
