name: test

on:
  pull_request:
  merge_group:
  
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
       name: production
    steps:
      - name: test
        run: curl -i -H "Authorization:Token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/user"
      - name: test2
        run: printenv
